#!/usr/bin/env python3
import os, sys
from pathlib import Path

def generate_header(filename, js_path, js_header_dir):
    with open(os.path.join(js_path, filename), 'r') as js_file:
        with open(os.path.join(js_header_dir, 'jsapp.h'), 'w') as header_file:
            header_file.write('#pragma once\n')
            header_file.write('static const jerry_char_t script[] = ""\n')
            for line in js_file:
                header_file.write('"{}"\n'.format(line.strip('\n').replace('"', '\\"')))

            header_file.write(';\n')
            header_file.write('static const jerry_length_t script_size = sizeof(script) - 1;\n')

js_dir = sys.argv[1]
js_header_dir = sys.argv[2]
print('Converting Javascript to C headers ...')
for filename in os.listdir(js_dir):
    if filename.endswith('.js'):
        generate_header(filename, js_dir, js_header_dir)

print('Converting Javascript to C headers ... COMPLETE')
